# WhatATheme
markdown: kramdown

# URL of the Site
url: 'https://www.murphelyria.com'
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: ""

# Title of the Site
title: Murph Elyria
# Description of the Site
description: Composer || Sound Designer || Creative
# URL of Image of the Site
site-image: /WhatATheme/assets/images/meta.jpg
# Keywords of the Site
site-keywords: Murph Elyria, Sound Designer, Film Composer
# URL for the Image of custom Favicon
favicon-url: /favicon.png

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: https://images.pexels.com/photos/210764/pexels-photo-210764.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: murphelyria@alum.calarts.edu
facebook_username: murph.elyria
twitter_username: MurphElyria
instagram_username: murphelyria
linkedin_username: murphelyria
github_username:  murphelyria
youtube_channel_id: UCM5ldhcw3jxl3kv2PNOS7Ig
reddit_username: 
behance_username: 
dribbble_username: 
spotify_username: 

# Google Analytics
# google-analytics: UA-code-here

# Disqus
# disqus-shortname: csrhymes

# Name of the Author
author-name: Murph Elyria
# URL for the Image of the Author
author-image: https://pbs.twimg.com/profile_images/1674538728487010305/B4RCePjP_400x400.jpg
# 60 Words About the Author
author-about: "As a sound designer, composer, voice actor, and video editor, Murph Elyria is a dynamic force in the creative world. Hailing from Sydney, Australia, Murph now calls Los Angeles home, crafting sonic landscapes for live theatre, film, independent YouTube content, and video games. They boast a versatile skillset, honed through diverse projects, culminating in a BFA from the California Institute of the Arts, specializing in Composition and Experimental Sound Practices with a focus on Film/TV Composition."
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://www.twitter.com/murphelyria

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: https://via.placeholder.com/1200x800
      description: "This is some placeholder text to be edited."
      tags:
        - "placeholder"
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
