title: Murph Elyria
description: Composer, Producer, Creative

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "projects"
    values:
      layout: "default"

collections:
  projects:
    output: true
    layout: "default"
